version: "2"
services:
  zeedle-server:
    container_name: zeedle-server
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
